<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Medical Report</title>
<link rel="stylesheet" href="style.css">
</head>

<body>

<div class="report-container">

    <!-- HEADER -->
    <div class="report-header">
        <h1>MedBridge</h1>
        <p>Patient Medical Report</p>
    </div>

    <!-- PHP DATA -->
    <?php
    $body = htmlspecialchars($_POST['body'] ?? '');
    $symptom = htmlspecialchars($_POST['symptom'] ?? '');
    $pain = htmlspecialchars($_POST['pain'] ?? '');
    $duration = htmlspecialchars($_POST['duration'] ?? '');
    $notes = htmlspecialchars($_POST['notes'] ?? '');
    
    include "db.php";
    $conn->select_db("medbridge");
    $stmt = $conn->prepare("INSERT INTO patients (body, symptom, pain, duration, notes) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param("ssiss", $body, $symptom, $pain, $duration, $notes);
    $stmt->execute();
    $stmt->close();
    $conn->close();
?>
    <!-- SECTION -->
    <div class="report-section">
        <h3>Patient Complaint</h3>
        <p><?php echo "$symptom in $body"; ?></p>
    </div>

    <div class="report-section">
        <h3>Duration</h3>
        <p><?php echo $duration; ?></p>
    </div>

    <div class="report-section">
        <h3>Pain Level</h3>
        <p><?php echo $pain; ?>/10</p>
    </div>

    <div class="report-section">
        <h3>Additional Notes</h3>
        <p><?php echo $notes ?: "No additional notes provided"; ?></p>
    </div>

    <!-- FOOTER -->
    <div class="report-footer">
        <p>Generated by MedBridge</p>
    </div>

    <!-- DOWNLOAD -->
    <button onclick="window.print()" class="print-btn">Download / Print Report</button>

</div>

</body>
</html>
</html>
<a href="view.php">
    <button type="button">View Records</button>
</a>
<td>
    <a href="delete.php?id=<?php echo $row['id']; ?>">
        Delete
    </a>
</td>